### ISSUE TITLE
Issue installing package

### ISSUE THREAD

**Issue by willbowdi** [alexander-akhmetov/python-shortcuts#10]
When trying to install the package I am getting the following error:

```
pip install shortcuts
Collecting shortcuts
  Using cached https://files.pythonhosted.org/packages/f1/cb/1924e5814706a0ef9140c0399c82a6a1257fb84756cd838684fd61732701/shortcuts-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Will\AppData\Local\Temp\pip-install-_62p5ag4\shortcuts\setup.py", line 19, in <module>
        readme = f.read()
      File "c:\users\will\python\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 277: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Will\AppData\Local\Temp\pip-install-_62p5ag4\shortcuts\
```

I've tried updating setuptools and have tried running as system admin to no luck

Windows 10 Home x64 happening on both Python 3.7.2 & 3.6.8

**Comment by alexander-akhmetov** [comment]
Hi, can you please try version `0.11.0`?

**Comment by willbowdi** [comment]
Thank you Alexander. That worked!
